### PR TITLE
db datas

### PR DESCRIPTION
**Pull request by Bryan-cf2m**
db datas

### CODE REVIEW

**Comment by McDibou** [comment]
- delete db_gabbler_sql.txt (sorry my bad)
- add data/db_gabbler.mwb.bak in file .gitignore
- add folder charte in data

**Comment by Bryan-cf2m** [comment]
done

**Comment by McDibou** [comment]
[Graphic charte](https://trello.com/c/8DwiZQUW/27-graphic-charte)

**Comment by McDibou** [comment]
[Conception database](https://trello.com/c/aecCK2cp/28-conception-database)

**Comment by McDibou** [comment]
[Conception database](https://trello.com/c/3BmquRsa/29-conception-database)

**Pull request merged**
